---
- name: hello world play
  hosts: all
  tasks:
    - name: debug hello world
      debug: 
        msg: Hello world from {{ ansible_facts.hostname }} v3
    - name: debug feature
      debug: 
        msg: this is feature 1 
